---

- name: "Create a temporary directory for job_logs"
  file:
    path: "/var/tmp/dci_{{ job_id }}_logs"
    state: directory
    mode: 0700
  register: job_logs

- name: "cnf-cert pre-run"
  include_role:
    name: cnf-cert
    tasks_from: pre-run.yml
  when: do_cnf_cert|bool

...
